google/stenographer

INSTALL.md, config/config.go, thread/thread.go
Some file systems have trouble with large numbers of files (ext3 can't handle
>32K files/directory).  Add a config option to limit the number of files created
before we start to delete them, and default it to 30K.
=> Add upper limit to #files/directory.

base/base.go, stenographer.go, stenotype/stenotype.cc, thread/thread.go
We had 'nobody', which isn't available by default on some systems.  'nogroup'
always should.
=> Switch default stenotype gid to 'nogroup'.

config/config.go, integration_test/test.sh
1) Config.go didn't correctly override max files
2) integration test didn't handle redirects
=> Simple fixes.

stenotype/aio.cc, stenotype/util.h
We used to have Errno() take a bool, and return an error if it was
false.  Now, we have Errno() take an int, and return an error if that
int is < 0.  However, we still appear to have a few cases floating
around where it is passed a bool.  Since a bool is either 0 or 1, this
means we never return an error. :(
Fixed in two places, and updated comment.
=> Fix error checking when opening files.

stenotype/stenotype.cc
Compiling on different Linux machines gives you calls to different
syscalls, which makes seccomp REALLY fun.  Here's a few more possible
calls.
=> Add additional syscalls which may be used.

README.md
Fixes the `before` timeout example in the README.
=> Fix UTC timestamp example

base/base.go, blockfile/blockfile.go, configs/systemd.conf, indexfile/indexfile.go, install_el7.sh
Depends on pull from @nbareil to fix the references to Google Code repos. Then, basically translated the install.sh script to function on CentOS 7, which depends on the EPEL repo. Lastly, I added a systemd service file that functions on CentOS 7.x. I haven't tested it on the new Ubuntu systemd support.
=> Added install script for EL7 and systemd support

config/config.go, configs/steno.conf, env/env.go, stenocurl
Currently Stenographer does not support listening on an external interface. With these changes you can configure it to listen externally. However, by default, only local listening is enabled (because listening externally has security implications).
This is some functionality that would be awesome for myself and my organization to have in the default Stenographer build. 
There is a known issue with this code that breaks stenoread when it is committed. This is because the certs are signed with the name 'localhost', where they no longer pointing. Instead, stenoread points to a new 'Host' parameter in the configuration file. If you choose to accept this, I'd rather find out how you would want the certificate generation to be changed than assume that myself. 
In our environment, we are just …
=> Add support for remote listening

stenographer.spec
This PR address issue #104. I'm not a golang expert, so I had to work around the 'go get ./...' which returns a non-zero response code. The build still succeeds, however.
The installation properly marks the POSIX capabilities and creates the necessary user on an EL7 system. It should work on similar RPM-based systems as well.
See [here](https://bintray.com/cyberdev/capes/stenographer/0.0-1.git89a9b66/view?sort=&order=#files) for an RPM binary.
=> Add RPM packaging support

blockfile/blockfile.go
When `stenoread` is used to query all packets in blocks,
struct 'allPacketsIter' is used.  The entire block
is read into 'allPacketsIter.blockData' and packets
to be sent to `stenoread` all refer to this byte slice.
Then, after one block is read, the blockfile module will
immediately load the next block.  Since the 'blockData'
is statically allocated, the loading of next block will
overwrite the data of yet to be sent packets, causing
corruption when `stenoread` tries to parse the packets
using `tcpdump`.
To fix it, this commit forces `allPacketsIter` function
to always `make([]byte, 1 << 20)` a new byte slice for
the next block, so that previous block data is always
retained until all packets in the block are sent to
`stenoread`.
Reported-by: Reid Price \<reid@awakenetworks.com\> …
=> blockfile: Fix overwriting 'blockData' before packet is read.

get-latest-steno, rpmbuild-steno-centos, stenographer.spec
Added centos 7 script that will check out latest version of stenographer from github and use rpmbuild and mock to create latest stenographer rpm using epel-7-x86_64 template. 
added dynamic git commit id detection to spec file so that you can use spec file will current master branch on github.
=> Added new file, correct spec file

install_el7.sh
Using 1.4 causes stenographer to misread client certificate and throw error. At the end whole stenographer was unusable.
Stenographer server:
```
Jul 21 12:09:49 localhost stenographer[15077]: 2016/07/21 12:09:49 http: TLS handshake error from 127.0.0.1:53398: tls: client's certificate's extended key usage doesn't permit it to be used for client authentication
```
cURL:
```
curl: (35) SSL peer was unable to negotiate an acceptable set of security parameters.
```
Stenocurl debug:
```
[root@localhost stenographer]# stenocurl /debug -v
* About to connect() to 127.0.0.1 port 1234 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 1234 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/stenographer/certs/ca_cert.pem
CApath: none
* NSS: client …
```
=> Sternographer needs at least Go 1.6

query/query.go
As the comment below (in query/query.go) says,
Note, we add a minute when doing 'before' queries and
subtract a minute when doing 'after' queries, to make
sure we actually get the time specified.
However, the current implementation does the opposite.
e.g. adds one minute when checking for skipping in the
'after' query:
if !a[0].IsZero() && t.Before(a[0].Add(time.Minute))
This commit swaps the adjustment.
Signed-off-by: Alex Wang \<alex@awakenetworks.com\>
=> query: Swap the time adjustment for time query lookup.

blockfile/blockfile.go
The formatting arguments were reversed, this corrects messages like:
Blockfile "host 1.2.3.4" looking up query "/tmp/stenographer0/PKT0/0"
to be:
Blockfile "/tmp/stenographer0/PKT0/0" looking up query "host 1.2.3.4"
=> blockfile: Correct order of strings in debug log

thread/thread.go
```
This modifies the sufficient log space message for threads from:
Thread 1 disk space is sufficient: 11 > 10
Thread 1 disk usage is high (packet path=/tmp/foobar): 10% < 10% free\n
to be:
Thread 1 disk space is sufficient (packet path=/tmp/foobar): 11% free > 10% threshold
Thread 1 disk usage is high (packet path=/tmp/foobar): 10% free <= 10% threshold
We also make minor additions to comments.
```
=> thread: Enrich and standardize disk usage logs

README.md
I tried to run "stenoread 'after 2012-11-03T11:05:00-0700'" based on query language examples in README.md, but an error occurred on my Debian sid server. I guess the timezone expression "-0700" may be "-07:00" according to RFC3339, and it worked fine on my server.
=> fix timezone expression on query language example

stenographer.spec
- Adds datestamp to revision to get proper ordering per Fedora [Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Versioning)
- Adds note to set static values before creating an SRPM. This fixes and issue that if you
package an SRPM today and then you compile it tomorrow, the commit and datestamp
may be incorrect.
- Adds changelog
- Other cleanup noted in Changelog
=> Adds datestamp and changelog to spec file

env/env.go
I was debugging HTTP headers and noticed this typo. Also, you should consider updating this to `application/vnd.tcpdump.pcap`, which is the [official mime type](http://www.netresec.com/?page=Blog&month=2011-04&post=PCAP-is-now-a-valid-MIME-type) for pcap.
=> Fix typo in mime header.

blockfile/blockfile.go, thread/thread.go
This fixes an edge case where steno can't delete files fast enough after
long periods of low traffic followed by sustained high traffic.
=> Delete oldest files based on newest file size.

stenotype/stenotype.cc
Some versions of leveldb need this.
=> Seccomp allow for getrlimit.

README.md
Took me a while to debug my app (https://github.com/rocknsm/docket) because I was parsing duration strings with Python libraries and rendering them to seconds as a common output. So `5m` would work, but when I converted it to `300.0s` it failed because "s" isn't supported, and the "." made the lexer assume it was an ip address. This note hopes to document that requirement.
=> Adds note about acceptable relative time values.

thread/thread.go
Relevant to Issue #167 
Root cause had to do with delCnt and len(files). If the file that was deleted wasn't enough to get below the required threshold, then the loop would continue, delCnt would be incremented, but if files was small - say a very small disk partition, then the index would cause a panic if the only file available to be deleted had been deleted and thus the len(files) was too small for the incremented delCnt.
(Second go at this - for whatever reason the merge from google/stenographer, which I did prior to the original PR, wasn't resolving the issue.)
=> Issue #167 Fix

install.sh
Upstart is no longer available in Ubuntu 18.04. This check should prevent the unnecessary attempt to install Upstart service files.
=> Ubuntu 18.04 install support

stenotype/stenotype.cc
Dear maintainers
Please accept this PR which fixes a couple of issues that has arisen due to the introduction of --blocksize_kb option.
In general these issue stem from the previous assumption that a block is 1MB.
The stats MBps and MB are wrong when bz!=1MB
Files are not rotated at the right time. Specifically, bz>1MB can lead to a PKT file larger than 4Gb which causes a fatal error.
To fix the issue, i've introduced a new variable blocks_per_file which is determined by the values flag_filesize_mband flag_blocksize_kb.
I'm not entirely sure whether the pattern of calculating blocks_per_file in the switch block is the right way to go.
NB: closed previous PR in order to create PR from company repo instead
=> fix bugs related to introduction of flag --blocksize_kb

integration_test/test.sh, query/query.go
At the moment, queries are always executed in their entirety against all index files (via `env.Lookup()` -> `thread.Lookup()` -> `blockfile.Lookup()`). See https://github.com/google/stenographer/blob/master/env/env.go#L274 and https://github.com/google/stenographer/blob/master/thread/thread.go#L346 etc..
That means that if a query cannot be satisfied in a block file, this information should be used as quickly as possible, to avoid doing useless queries before moving on to the next block file. For example, when doing time-based queries, it would be highly beneficial to quickly skip all block files that cannot satisfy the time constraint. Note that the time constraint is efficiently checked for the `timeQuery.LookupIn()` (https://github.com/google/stenographer/blob/master/query/query.go#L183 …
=> query: improve performance of queries using Boolean operators

stenotype/Makefile, stenotype/util.h
This PR is a collaboration between @lassulus and me. 
When running Stenographer for a long stretch of time, Stenographer's time-based index look-ups get increasingly (though slowly) less accurate due to a clock skew affecting the timestamped index file names.
This error can be observed best, by tracking the difference between an index filename and its creation time over a long period of time (on our system we noticed ~ 5 seconds per day, but this will definitely vary between environments). Ultimately,  queries submitted via `stenoread` require an ever larger time-bracket for a successful response, though the actual packets returned will show the expected timestamp. 
The time drift originates in using monotonic time measurements, i.e., `CLOCK_MONOTONIC` or rather `CLOCK_MONOTONIC_RAW`.  We …
=> bug: slowly increasing time drift tampers with index look-ups

config/config.go, env/env.go
Stenotype has an option for using testimony socket (if compiled with testimony support), but
there was no way to use it with stenographer.
=> Add testimony socket config option to stenographer

stenotype/stenotype.cc
Hi,
I had issues to get stenographer working in Ubuntu 18.04 (cf. #205). After a while of digging, I found out that they were SECCOMP related - I faced no issues when running stenographer with the "--seccomp=none" flag. 
What fixed it for me in the end, was to add two new SECCOMP rules for prlimit64 and openat. This pull requests adds those two rules.
=> added seccomp rules for prlimit64 and openat calls

stenotype/stenotype.cc
Wanted to not show stats every time you blink.
Can disable with 0s or only display by size or time.
=> add flags for stats block size and seconds

stenotype/stenotype.cc
"Privileges" is misspelled in some output. Just upstreaming small patches from Debian packaging so we can drop them there :)
=> small spelling fix
